### ISSUE TITLE
group @all ignored

### ISSUE THREAD

**Issue by bomhard** [cosmocode/dokuwiki-plugin-acknowledge#2]
`~~ACK:<@all>~~ is not working, neither is ~~ACK:<@ALL>~~ or ~~ACK:<someuser,@all>~~ or ~~ACK:<someuser,@ALL>~~ `

However, the users are handled correctly.

**Comment by annda** [comment]
This is expected. `@ALL` is a virtual group that only has meaning in ACL context. It cannot be user for group matching in other contexts. Use `@user` or whatever name you have defined as [default group name](https://www.dokuwiki.org/config:defaultgroup)
