### ISSUE TITLE
See all pages that have not been acknowledged for all users?

### ISSUE THREAD

**Issue by gw72** [cosmocode/dokuwiki-plugin-acknowledge#3]
This is a really useful plugin.
Is there anyway for an admin user to see all pages that require acknowledgement that have not been acknowledged (for all other users).
An individual user can see pages they are required to acknowledge and an admin user can see all pages that have been acknowledged, but I cannot see how an admin user can check which users have still not acknowledged everything they should.

**Comment by jzaers** [comment]
I support this feature request.

**Comment by annda** [comment]
The admin interface has been extended: now you can check due acknowledgements per user or per page / namespace.
