### ISSUE TITLE
helper.php - array index on null

### ISSUE THREAD

**Issue by mr-sven** [cosmocode/dokuwiki-plugin-acknowledge#8]
If `queryRecord` returns null a warning happend.
https://github.com/cosmocode/dokuwiki-plugin-acknowledge/blob/82c25c0b32fb132a975008848f7eefc39f4a4139/helper.php#L245

fix:
```patch
        $record = $sqlite->queryRecord($sql, $page);
++      if (!$record) return false;
        $assignees = $record['pageassignees'] . ',' . $record['autoassignees'];
```

**Comment by splitbrain** [comment]
can you send a PR please?
